### ISSUE TITLE
ATIS partition sizes

### ISSUE THREAD

**Issue by tomsherborne** [sriniiyer/nl2sql#3]
In the paper and in other ATIS version, the total dataset size is 5418 utterances split as 4473 Training examples, 497 development examples and 448 test examples. 

Looking at /data/atis/{train,dev,test}.{nl,sql} in this repo, I've counted 4379 training examples, 491 development examples and 448 test examples totaling 5318 examples.

Apologies if I've missed this in the docs or paper, but can you explain where 100 examples in the train+dev set have gone? Thanks

**Comment by sriniiyer** [comment]
Apologies for the delayed response. Those are probably examples where writing the SQL query was either not possible or was ambiguous. The test set still contains the same number of examples and final results should be reported on the test set for model comparison. The dev set is missing only 6 examples, so it shouldn't affect results much.
